name: Update rules

on:
  push:
  schedule:
    - cron: 0 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get rules
      run: |
        sudo apt install -y dos2unix rename
        chmod 755 common/configs_update.sh
        ./common/configs_update.sh
        TMPDIR=/tmp
        rm -rf config/rules/
        cp -r $TMPDIR/smartdns/ config/rules/
        cp $TMPDIR/smartdns.tar.xz config/rules/
        cp -r . $TMPDIR/module/
        rm -rf $TMPDIR/module/LICENSE $TMPDIR/module/.git* $TMPDIR/module/README.md
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: magisk_module
        path: /tmp/module/
    - name: Commit rules
      uses: zwaldowski/git-commit-action@v1
      with:
        commit_message: Automated update rules
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: $\{{ secrets.GITHUB_TOKEN }}
